-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "currentQuarter" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "isOvertime" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "overtimeLength" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN     "quarterLength" INTEGER NOT NULL DEFAULT 720,
ADD COLUMN     "quarterTime" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalQuarters" INTEGER NOT NULL DEFAULT 4;
